name: build

on: [push]

jobs:
  build:
    runs-on: self-hosted
    container: python:${{ matrix.python-version }}-ubuntu18.04-basic
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      run: |
        apt update
        apt install build-essential
        apt install -y python${{ matrix.python-version }} python${{ matrix.python-version }}-dev python3-pip
        python${{ matrix.python-version }} -m pip install pip setuptools wheel pybind11 --upgrade
        if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi
        if [ ! -e /usr/bin/pip ]; then ln -s /usr/local/bin/pip3 /usr/bin/pip ; fi
    - name: Install dependencies
      run: |
        apt install -y zlib1g-dev libjpeg-dev libtiff-dev
        pip install -r requirements.txt
    - name: Run static analyses
      run: |
        # stop the build if there are Python syntax errors, undefined symbols or failed code style checks
        # python -m pylint -f parseable src --disable=bad-continuation,fixme  # disable bad-continuation checks due https://github.com/PyCQA/pylint/issues/289
        # pycodestyle src
    - name: Run tests
      run: |
        coverage run --source=src ./setup.py test
        # stop the build if the test coverage is under 80%
        # coverage report --fail-under=80
